### PR TITLE
Add brand prefixes for fontawesome icons

### PR DESCRIPTION
**Pull request by apreshill**
Noticed some of your icons in the upper navbar were broken, this one bit me too!

### CODE REVIEW

**Review by gadenbuie — COMMENTED** [review]
Thanks! I've seen this in more than a few places and have been meaning to dig into it!

**Comment by cderv** [comment]
No need to dig it more, this is a known issue https://github.com/rstudio/rmarkdown/issues/1991 and there is already a PR that I think solves it. 

Sorry for the trouble 😄

**Comment by gadenbuie** [comment]
Thanks @cderv (for telling me after I went and updated 6 other repos 😜)! Seriously though, am I reading that issue right that you'll make FA4 work but that using the FA5 prefixes is probably the safest option in the future?

**Comment by cderv** [comment]
> Seriously though, am I reading that issue right that you'll make FA4 work but that using the FA5 prefixes is probably the safest option in the future?

The story is that 
* **rmarkdown** did upgrade to FA5 (https://github.com/rstudio/rmarkdown/pull/1340)
* but the new prefixes where not supported in navbar, so I extended support in https://github.com/rstudio/rmarkdown/pull/1967 making the new prefix `fas` the default
* But this broke some stuff (the issue you read) that where working without any prefix because it was added but rmarkdown. Hence the last PR (https://github.com/rstudio/rmarkdown/pull/1994)

So FA4 will work without the prefix changes for what is included in the shims file for compatibility (https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/h/fontawesome/css/v4-shims.css following https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#manually). 
So **rmarkdown** will do as before and add `fa` prefix for you. This will work for everything that works with the compatibility layer, but it is best to provide the correct prefix to select icons now. 

Does it seem not right to you ? 

We could try being more clever and try to decide the right prefix, but it seemed a bit too much. If you want to dicuss it, I'll be happy too.

**Comment by cderv** [comment]
In fact, I looked into how **shiny** handles it and they maintain a list of fontawesome brand icon. When one is detected the `fab` prefix is used.

I think this can follow up this path to make easily updated and so that just the name of the icon can be passed. No prefix needed then. 

Thanks for challenging this !

**Pull request merged**
